== Hoverfly JUnit Rule

image:https://circleci.com/gh/SpectoLabs/hoverfly-junit.svg?style=shield["CircleCI", link="https://circleci.com/gh/SpectoLabs/hoverfly-junit"]
image:https://codecov.io/gh/spectolabs/hoverfly-junit/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/spectolabs/hoverfly-junit"]
image:https://img.shields.io/maven-central/v/io.specto/hoverfly-junit.svg["Maven Central", link="https://mvnrepository.com/artifact/io.specto/hoverfly-junit"]

A Java native language binding for http://hoverfly.io/[Hoverfly^], which allows you to simulate http services in your unit tests.

=== Legacy Schema Migration
If you have recorded data in the legacy schema generated before hoverfly-junit v0.1.9, you will need to run the following commands using http://hoverfly.io/[Hoverfly^] to migrate to the new schema:
```bash
$ hoverctl start
$ hoverctl delete simulations
$ hoverctl import --v1 path-to-my-json/file.json
$ hoverctl export path-to-my-json/file.json
$ hoverctl stop
```

=== Quick Start

Simply add the following rule to your class, giving it the path to your Simulation on the ClassPath.

[source,java,indent=0]
----
@Rule
public HoverflyRule hoverflyRule = HoverflyRule.inSimulationMode("test-hoverflyStubService.json");
----

As Hoverfly is a proxy, all requests (assuming they respect the JVM proxy settings) will be routed through it.  Hoverfly will then respond instead of the real hoverflyStubService.

The rule will attempt to detect the operating system and architecture type of the host, and then extract and execute the correct hoverfly binary.  It will import the json into it's database and then and destroy the process at the end of the tests.

<<<<<<< 1f6be88c28b25c8be2d279c8759b9a6241a2b3f0
==== Maven Build
Import to your Maven project:
=======
=== DSL
