== Hoverfly Java - Easy creation of stub servers for testing

image:https://circleci.com/gh/SpectoLabs/hoverfly-java.svg?style=shield["CircleCI", link="https://circleci.com/gh/SpectoLabs/hoverfly-java"]
image:https://codecov.io/gh/spectolabs/hoverfly-java/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/spectolabs/hoverfly-java"]
image:https://img.shields.io/maven-central/v/io.specto/hoverfly-java.svg["Maven Central", link="https://mvnrepository.com/artifact/io.specto/hoverfly-java"]

A Java native language binding for http://hoverfly.io/[Hoverfly^], a Go proxy which allows you to simulate http services in your unit tests. Another term
for this is Service Virtualisation[https://en.wikipedia.org/wiki/Service_virtualization].

== Features

- Simulation of http services
- Strict or loose http request matching based on URL, method, body and header combinations
- Fluent and expressive DSL for easy generation of simulated services
- Create simulations by running in capture mode
- Hoverfly is a proxy, so you don't need to alter the host that you make requests to
- Multiple hosts / services per single instance of Hoverfly
- Https automatically supported, no extra configuration required
- Interoperable with standard Hoverfly json, making it easy to re-use data between Java and other bindings.

Full documentation is available here[http://hoverfly-java.specto.io]

== Contributions

Contributions are welcome!

To submit a pull request you should fork the Hoverfly-Java repository, and make your change on a feature branch of your fork.

== Issues

Feel free to raise an issues on Github.

== License

Apache License version 2.0.

(c) SpectoLabs 2016.


